openapi: 3.0.0
paths:
  /tasks:
    get:
      security:
        - bearerAuth: []
      tags:
        - Tasks
      operationId: TasksController_getTasks
      parameters: []
      responses:
        "200":
          description: ""
    post:
      security:
        - bearerAuth: []
      tags:
        - Tasks
      operationId: TasksController_createTask
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTaskDto"
      responses:
        "201":
          description: ""
  /tasks/{id}:
    get:
      security:
        - bearerAuth: []
      tags:
        - Tasks
      operationId: TasksController_getTaskById
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        "200":
          description: ""
    delete:
      security:
        - bearerAuth: []
      tags:
        - Tasks
      operationId: TasksController_deleteTask
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        "200":
          description: ""
  /tasks/{id}/status:
    patch:
      security:
        - bearerAuth: []
      tags:
        - Tasks
      operationId: TasksController_updateTask
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        "200":
          description: ""
  /auth/signup:
    post:
      tags:
        - Auth
      operationId: AuthController_signUp
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthCredentialsDto"
      responses:
        "201":
          description: ""
  /auth/signin:
    post:
      tags:
        - Auth
      operationId: AuthController_signIn
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthCredentialsDto"
      responses:
        "201":
          description: ""
info:
  title: Task API
  description: ""
  version: "1.0"
  contact: {}
tags:
  - name: Tasks
    description: Tasks management
  - name: Auth
    description: User Authentication
servers:
  - url: http://localhost:3000
components:
  schemas:
    CreateTaskDto:
      type: object
      properties: {}
    AuthCredentialsDto:
      type: object
      properties: {}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
