openapi: 3.0.0
paths:
  /tasks:
    get:
      security:
        - bearerAuth: []
      tags:
        - Tasks
      parameters:
        - in: query
          name: status
          schema:
            type: string
            enum: [OPEN, IN_PROGRESS, DONE]
          description: The status of tasks to filter
        - in: query
          name: search
          schema:
            type: string
          description: The search term, it will search by title and description
      operationId: TasksController_getTasks
      responses:
        "200":
          description: A list of tasks
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ArrayOfTasks"
        "401":
          description: Authorization information is missing or invalid.
        "5XX":
          description: Unexpected error.
    post:
      security:
        - bearerAuth: []
      tags:
        - Tasks
      operationId: TasksController_createTask
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTaskDto"
      responses:
        "201":
          description: Created
        "401":
          description: Authorization information is missing or invalid.
        "5XX":
          description: Unexpected error.
  /tasks/{id}:
    get:
      security:
        - bearerAuth: []
      tags:
        - Tasks
      operationId: TasksController_getTaskById
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        "200":
          description: A task
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "401":
          description: Authorization information is missing or invalid.
        "404":
          description: A task with the specified ID was not found.
        "5XX":
          description: Unexpected error.
    delete:
      security:
        - bearerAuth: []
      tags:
        - Tasks
      operationId: TasksController_deleteTask
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        "200":
          description: "Deleted"
        "401":
          description: Authorization information is missing or invalid.
        "404":
          description: A task with the specified ID was not found.
        "5XX":
          description: Unexpected error.
  /tasks/{id}/status:
    patch:
      security:
        - bearerAuth: []
      tags:
        - Tasks
      operationId: TasksController_updateTask
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      requestBody:
        description: Status of the task
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskStatus"
      responses:
        "200":
          description: "Updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "401":
          description: Authorization information is missing or invalid.
        "404":
          description: A task with the specified ID was not found.
        "5XX":
          description: Unexpected error.
  /auth/signup:
    post:
      tags:
        - Auth
      operationId: AuthController_signUp
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthCredentialsDto"
      responses:
        "201":
          description: "Signed up"
        "409":
          description: "Username already exists"
        "5XX":
          description: Unexpected error.
  /auth/signin:
    post:
      tags:
        - Auth
      operationId: AuthController_signIn
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthCredentialsDto"
      responses:
        "201":
          description: "Signed in"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccessToken"
        "401":
          description: Invalid credentials
        "5XX":
          description: Unexpected error.
info:
  title: Task API
  description: ""
  version: "1.0"
  contact: {}
tags:
  - name: Tasks
    description: Tasks management
  - name: Auth
    description: User Authentication
servers:
  - url: http://localhost:3000
components:
  schemas:
    AccessToken:
      type: object
      properties:
        accessToken:
          type: string
    CreateTaskDto:
      type: object
      required:
        - title
        - description
      properties:
        title:
          type: string
        description:
          type: string
    AuthCredentialsDto:
      type: object
      properties:
        username:
          type: string
          minimum: 4
          maximum: 20
        password:
          type: string
          minimum: 8
          maximum: 20
    ArrayOfTasks:
      type: array
      items:
        $ref: "#/components/schemas/Task"
    Task:
      type: object
      properties:
        id:
          type: number
        title:
          type: string
        description:
          type: string
        status:
          type: string
          enum: [OPEN, IN_PROGRESS, DONE]
        userId:
          type: number
    TaskStatus:
      type: object
      properties:
        status:
          type: string
          enum: [OPEN, IN_PROGRESS, DONE]
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
