openapi: 3.0.0
paths:
  /tasks:
    get:
      security:
        - bearerAuth: []
      tags:
        - Tasks
      parameters:
        - in: query
          name: status
          schema:
            type: string
            enum: [OPEN, IN_PROGRESS, DONE]
          description: The status of tasks to filter
        - in: query
          name: search
          schema:
            type: string
          description: The search term, it will search by title and description
      operationId: TasksController_getTasks
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ArrayOfTasks"
    post:
      security:
        - bearerAuth: []
      tags:
        - Tasks
      operationId: TasksController_createTask
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTaskDto"
      responses:
        "201":
          description: ""
  /tasks/{id}:
    get:
      security:
        - bearerAuth: []
      tags:
        - Tasks
      operationId: TasksController_getTaskById
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        "200":
          description: ""
    delete:
      security:
        - bearerAuth: []
      tags:
        - Tasks
      operationId: TasksController_deleteTask
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        "200":
          description: ""
  /tasks/{id}/status:
    patch:
      security:
        - bearerAuth: []
      tags:
        - Tasks
      operationId: TasksController_updateTask
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        "200":
          description: ""
  /auth/signup:
    post:
      tags:
        - Auth
      operationId: AuthController_signUp
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthCredentialsDto"
      responses:
        "201":
          description: ""
  /auth/signin:
    post:
      tags:
        - Auth
      operationId: AuthController_signIn
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthCredentialsDto"
      responses:
        "201":
          description: ""
info:
  title: Task API
  description: ""
  version: "1.0"
  contact: {}
tags:
  - name: Tasks
    description: Tasks management
  - name: Auth
    description: User Authentication
servers:
  - url: http://localhost:3000
components:
  schemas:
    CreateTaskDto:
      type: object
      required:
        - title
        - description
      properties:
        title:
          type: string
        description:
          type: string
    AuthCredentialsDto:
      type: object
      properties: {}
    ArrayOfTasks:
      type: array
      items:
        $ref: "#/components/schemas/Task"
    Task:
      type: object
      properties:
        id:
          type: number
        title:
          type: string
        description:
          type: string
        status:
          type: string
        userId:
          type: number
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
